# Site settings
title: Nicholas A. Kraft, PhD
author:
  name: Nicholas A. Kraft
  email: nicholas.a.kraft@us.abb.com
  github:  nkraft
  twitter: nicholasakraft
description: Nicholas Nick Kraft
baseurl: ""
url: "http://nicholasakraft.com"
analytics:
  google:
    tracking_id: 'UA-55940147-1'

# Build settings
timezone: America/New_York
encoding: utf-8
markdown: kramdown
permalink: pretty
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
